# Generated by Django 2.0.4 on 2018-04-16 07:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(db_column='班级名', max_length=20)),
                ('gdate', models.DateTimeField(db_column='创建时间')),
                ('ggirlnum', models.IntegerField(db_column='女生数量')),
                ('gboynum', models.IntegerField(db_column='男生数量')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'grades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(db_column='姓名', max_length=20)),
                ('sgender', models.BooleanField(db_column='性别', default=True)),
                ('sage', models.IntegerField(db_column='年龄')),
                ('scountend', models.CharField(db_column='描述', max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('lastTime', models.DateTimeField(auto_now=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('sgrade', models.ForeignKey(db_column='班级', on_delete=django.db.models.deletion.CASCADE, to='myApp.Grades')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['id'],
            },
            managers=[
                ('stuObj', django.db.models.manager.Manager()),
            ],
        ),
    ]
